USE [master]
GO

/****** Object:  Database [EyesTest]    Script Date: 6/23/2023 4:49:52 PM ******/
CREATE DATABASE [EyesTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EyesTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.NVMSSQLSERVER\MSSQL\DATA\EyesTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EyesTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.NVMSSQLSERVER\MSSQL\DATA\EyesTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EyesTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EyesTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EyesTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EyesTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EyesTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EyesTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [EyesTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EyesTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EyesTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EyesTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EyesTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EyesTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EyesTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EyesTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EyesTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EyesTest] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EyesTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EyesTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EyesTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EyesTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EyesTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EyesTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EyesTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EyesTest] SET RECOVERY FULL 
GO

ALTER DATABASE [EyesTest] SET  MULTI_USER 
GO

ALTER DATABASE [EyesTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EyesTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EyesTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EyesTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EyesTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EyesTest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EyesTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EyesTest] SET  READ_WRITE 
GO

